name: iDlife
favicon: null
layout_spectrum: 0.5383830147329718
typography_spectrum: 0.9670419981703162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.890591062605381
  lightness: 0.8237839294597507
  saturation: 0.11163430451415479
  rhythmicContrast: 0.10499768913723528
purpose: []
