name: iDlife
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00954
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8bc3dc'
    - '#040404'
    - '#d3e7f2'
    - '#794108'
    - '#a3886b'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
